(import ../src/powerspike/fitness-cache :as cache)
(import ../src/powerspike/search :as search)
(import ../src/powerspike/packages :as packages)
(import ../src/powerspike/scenario :as scenario)
(import ../src/powerspike/jobs :as jobs)
(import ../src/powerspike/data-util :as util)
(import pshash :as hash)

# Cached results are immutable snapshots; callers cannot change later scores.
(def source @{:metrics @{:damage 42} :unsupported @[]})
(cache/store "frozen" source)
(put (source :metrics) :damage 99)
(assert (= 42 (get-in (cache/lookup "frozen") [:metrics :damage])))
(assert (not (first (protect (put ((cache/lookup "frozen") :metrics) :damage 100)))))
(cache/clear)
(for index 0 cache/capacity (cache/store (string index) {:metrics {:damage index}}))
(cache/lookup "0")
(cache/store "new" {:metrics {:damage 0}})
(assert (cache/lookup "0"))
(assert (not (cache/lookup "1")))
(assert (= cache/capacity ((cache/stats) :entries)))
(cache/clear)
(def large (string/repeat "x" (* 3 1024 1024)))
(each key ["a" "b" "c"] (cache/store key {:unsupported [large]}))
(assert (= 2 ((cache/stats) :entries)))
(assert (not (cache/lookup "a")))
(assert (<= ((cache/stats) :bytes) cache/byte-limit))
(assert (not (cache/store "oversize" {:unsupported [(string/repeat "y" cache/byte-limit)]})))
(def delta (cache/export-changes))
(cache/clear)
(cache/accept-changes delta)
(assert (= 2 ((cache/stats) :entries)))
(cache/clear)

(def root (string "/tmp/powerspike-fitness-" (hash/sha256 (os/cryptorand 8))))
(packages/initialize root "build/seed")
(def pack (packages/load "16.19.1"))
(def definition {:schema 1 :patch (pack :patch) :snapshot (pack :snapshot) :duration 1.5 :distance 100 :seed 3 :samples 1
                 :player {:champion "Annie" :level 6 :loadout {:items []}} :target {:kind :practice :hp 10000 :armor 80 :mr 80}})
(def options {:pool ["1052" "1036"] :slots 1 :budget 1000 :seconds 2 :samples 1 :final-samples 1})
(defn run [candidate settings] (search/run pack candidate settings (fn [p] nil) (fn [] false)))
(def cold (run definition options))
(def warm (run definition options))
(assert (= 3 (cold :simulated)))
(assert (= 0 (warm :simulated)))
(assert (= 3 (warm :cache-hits)))
(assert (= (util/canonical (map |($ :metrics) (cold :rows))) (util/canonical (map |($ :metrics) (warm :rows)))))
# Constraints and scoring are applied anew even when combat metrics are reused.
(def cheaper (run definition (merge options {:budget 399 :preset :sustained})))
(assert (= 0 (cheaper :simulated)))
(assert (= 2 (cheaper :cache-hits)))
(each row (cheaper :rows) (assert (<= (row :cost) 399)))
(def target-changed (merge definition {:target (merge (definition :target) {:mr 0})}))
(def changed (run target-changed options))
(assert (= 0 (changed :cache-hits)))
(assert (> (get-in changed [:rows 0 :metrics :damage]) (get-in cold [:rows 0 :metrics :damage])))
(def sampled (run definition (merge options {:final-samples 4})))
(assert (= 0 (sampled :cache-hits)))
(each row (sampled :rows) (assert (= 4 (row :samples))))
(def key (search/fitness-key pack definition))
(each candidate [(merge definition {:seed 4}) (merge definition {:duration 2}) (merge definition {:distance 200})
                 (merge definition {:samples 4}) target-changed
                 (merge definition {:player (merge (definition :player) {:health-fraction 0.5})})
                 (merge definition {:player (merge (definition :player) {:resource-fraction 0.5})})
                 (merge definition {:player (merge (definition :player) {:strategy {:attacks false}})})
                 (merge definition {:player (merge (definition :player) {:ranks {:q 1}})})
                 (merge definition {:player (merge (definition :player) {:loadout {:items [] :runes [8112]}})})]
  (assert (not= key (search/fitness-key pack candidate))))
(assert (not= key (search/fitness-key (merge pack {:patch "16.18.1"}) definition)))
(assert (not= key (search/fitness-key (merge pack {:snapshot "different"}) definition)))
(assert (not= key (search/fitness-key pack (merge definition {:model "different"}))))
# Trace-free fitness agrees with the ordinary frontend simulation, including
# all aggregate metrics, uncertainty and explicit unsupported components.
(def normal (scenario/simulate (merge definition {:samples 4})))
(def fitness (scenario/fitness (merge definition {:samples 4})))
(each field [:metrics :uncertainty :unsupported] (assert (= (util/canonical (normal field)) (util/canonical (fitness field)))))
(cache/clear)
(var checks 0)
(def cancelled (search/run pack definition (merge options {:final-samples 32}) (fn [p] nil)
                           (fn [] (++ checks) (> checks 8))))
(assert (cancelled :cancelled))
(assert (= 0 ((cache/stats) :entries)))

# A fresh thread must reuse results from an earlier completed worker. Job
# cancellation remains a separate capability even for identical scenarios.
(defn work [input progress cancelled]
  (search/run (packages/load (get-in input [:definition :patch]) (get-in input [:definition :snapshot]))
              (input :definition) (input :options) progress cancelled))
(defn await [job]
  (def deadline (+ (os/clock :monotonic) 10))
  (while (not (jobs/terminal? job))
    (assert (< (os/clock :monotonic) deadline) "Worker failed to finish.") (ev/sleep 0.01))
  (assert (= :done (job :status)) (job :error)) (job :result))
(def first-job (await (jobs/submit :optimization "cache-cold" work {:definition definition :options options})))
(def next-job (await (jobs/submit :optimization "cache-warm" work {:definition definition :options options})))
(assert (= 3 (first-job :simulated)))
(assert (= 0 (next-job :simulated)))
(assert (= 3 (next-job :cache-hits)))
(assert (= (util/canonical (map |($ :metrics) (first-job :rows))) (util/canonical (map |($ :metrics) (next-job :rows)))))
(defn cancellable [value progress cancel]
  (progress {:message "Working" :completed 1})
  (os/sleep 0.1)
  (when (cancel) (error "Cancelled.")) value)
(def cancelled-job (jobs/submit :optimization "independent-a" cancellable 1))
(def unaffected-job (jobs/submit :optimization "independent-b" cancellable 2))
(jobs/cancel (cancelled-job :id))
(jobs/cancel (cancelled-job :id))
(assert (= 2 (await unaffected-job)))
(assert (= :cancelled (cancelled-job :status)))
(assert (not (cancelled-job :cancel-channel)))
(assert (not (unaffected-job :cancel-requested)))
(cache/clear)
(util/remove-tree root)
(print "Bounded LRU fitness cache, immutable values, complete identities, constraints, trial schedules, partial cancellation and cross-worker reuse passed.")
