(import ../src/powerspike/normalize :as normalize)
(import ../src/powerspike/packages :as packages)
(import ../src/powerspike/scenario :as scenario)
(import ../src/powerspike/engine :as engine)
(import ../src/powerspike/search :as search)
(import ../src/powerspike/data-util :as util)
(import ../web/catalog :as catalog)
(import ../web/model :as model)
(import ../web/ui :as ui)
(import ../web/optimizer :as optimizer)
(import pshash :as hash)

(def fixtures "data/combat-fixtures/16.19.1/")
(def manifest (util/read-json (slurp (string fixtures "manifest.json"))))
(eachp [path expected] (manifest "fixture_sha256")
  (assert (= expected (hash/sha256 (slurp (string fixtures path)))) "Mage fixture corruption."))
(def fonts (util/read-json (slurp (string fixtures "champion-strings.json"))))
(def records (util/read-json (slurp (string fixtures "items.json"))))
(def dd ((util/read-json (slurp (string fixtures "items-ddragon.json"))) "data"))
(def items (map |(normalize/item-effects (normalize/item "16.19.1" $ (dd $)) records {}) (keys dd)))
(defn raw-champion [id]
  (def objects (util/read-json (slurp (string fixtures id "-characters.json"))))
  (def detail (util/read-json (slurp (string fixtures id "-abilities.json"))))
  (def dd (get-in detail ["data" id]))
  (def paths (normalize/spell-paths id (objects (string "Characters/" id "/CharacterRecords/Root"))))
  # Deliberately retain the old generic effects: loading an existing snapshot
  # must apply the current semantics without a download or new snapshot.
  (merge (normalize/champion "16.19.1" dd objects)
         {:abilities (map (fn [slot path source] (normalize/ability slot path (objects path) source fonts "16.19.1"))
                          [:q :w :e :r] paths (dd "spells"))}))
(def champions (map raw-champion ["Annie" "Viktor" "Ahri"]))
# The browser validates its unused default opponent in practice mode too.
(array/push champions (find |(= "Garen" ($ :id)) ((util/read-data "data/16.19.1/catalog/catalog.jdn") :champions)))
(def root (string "build/mage-burst-tests/" (hash/sha256 (os/cryptorand 8))))
(def bytes (util/encode-data (util/canonical {:schema 1 :parser "4" :patch "16.19.1" :champions champions :items items})))
(def snapshot (hash/sha256 bytes))
(def directory (string root "/patches/16.19.1/" snapshot))
(util/write (string directory "/package.jdn") bytes)
(util/write (string directory "/manifest.json") (util/encode-json {"initial" false "package_sha256" snapshot}))
(util/write (string root "/patches/16.19.1/current") snapshot)
(def package (catalog/initialize root nil))
(assert (= snapshot (package :snapshot)))
(assert (= snapshot (hash/sha256 (slurp (string directory "/package.jdn")))))
(each champion (package :champions)
  (assert (= (string (util/encode-data (util/canonical champion)))
             (string (util/encode-data (util/canonical (normalize/semantic-kit (champion :id) "16.19.1" champion)))))
          "Semantic rules must be idempotent."))
(defn close [expected actual] (assert (< (math/abs (- expected actual)) 0.0001)))
(defn definition [champion ids &opt input]
  (model/definition (model/parse-state (merge {"champion" champion "opponent" "Annie" "selected" "custom"} (or input {}))) ids))
(defn isolated [champion slot &opt fields duration]
  (def compiled (scenario/compile (definition champion [])))
  (def actor ((compiled :actors) 0))
  (engine/simulate {:duration (or duration 3)
                    :actors [(merge actor {:ranks {:q 1 :w 1 :e 1 :r 3}
                                           :stats (merge (actor :stats) {:ad 150 :ap 100 :attack-speed 1 :mp 1000 :mp-regen 0})
                                           :strategy {:abilities true :attacks false :priority [slot] :movement :hold}} (or fields {}))
                             {:id "target" :kind :practice :tags [:practice :champion] :level 1 :position 0
                              :stats {:hp 100000 :armor 0 :mr 0} :strategy {:attacks false :abilities false}}]}))
(def q (isolated "Viktor" :q {:strategy {:abilities true :attacks true :priority [:q] :movement :hold}}))
(def q-hits (filter |(= "ViktorQ" ($ :source)) (q :events)))
(assert (= 2 (length q-hits)))
(close 100 ((q-hits 0) :damage))
(close 220 ((q-hits 1) :damage))
(assert (= :magic ((q-hits 1) :type)))
(close 620 (q :damage)) # Q missile, empowered attack, then two ordinary attacks.
(assert (= 1 (length (filter |(= "ViktorQ" ($ :source)) ((isolated "Viktor" :q) :events)))))
(def storm (isolated "Viktor" :r nil 7))
(def storm-hits (filter |(= "ViktorR" ($ :source)) (storm :events)))
(assert (= 7 (length storm-hits)))
(close 300 ((storm-hits 0) :damage))
(for index 1 7
  (close 180 ((storm-hits index) :damage))
  (close 1 (- ((storm-hits index) :at) ((storm-hits (dec index)) :at))))
(close 1380 (storm :damage))
(close 300 ((isolated "Viktor" :r nil 0.5) :damage))
(def rush (isolated "Ahri" :r))
(def rush-hits (filter |(= "AhriR" ($ :source)) (rush :events)))
(assert (= 3 (length rush-hits)))
(close 630 (rush :damage))
(close 1 (- ((rush-hits 1) :at) ((rush-hits 0) :at)))
(close 1 (- ((rush-hits 2) :at) ((rush-hits 1) :at)))
(def casts (filter |(= :cast ($ :kind)) (rush :trace)))
(assert (= 3 (length casts)))
(close 100 (sum (map |($ :cost) casts)))

(def pool ["3089" "3135" "6655" "3100" "3115" "3153" "3046" "3087"])
(each champion ["Annie" "Viktor" "Ahri"]
  (def state (model/parse-state {"champion" champion "opponent" "Annie" "selected" "custom"}))
  (assert (= 2500 (state :target-health)))
  (def candidate (model/definition state []))
  (def ap (scenario/fitness (definition champion ["3089" "3135" "6655"])))
  (def ad (scenario/fitness (definition champion ["3153" "3046" "3087"])))
  (assert (> (get-in ap [:metrics :damage]) (get-in ad [:metrics :damage])))
  (def outcome (search/run package candidate {:pool pool :preset :burst :budget 10000 :slots 3 :seconds 10 :final-samples 1}
                           (fn [p] nil) (fn [] false)))
  (assert (outcome :complete))
  (def best (first (outcome :rows)))
  (assert (>= (get-in best [:metrics :damage]) (get-in ap [:metrics :damage])))
  (def compiled (scenario/compile (best :definition)))
  (assert (> (get-in compiled [:actors 0 :stats :ap]) (get-in compiled [:actors 0 :stats :bonus-ad])))
  (each row (outcome :rows) (assert (<= (row :cost) 10000)))
  (def heuristic (search/run package candidate {:preset :burst :budget 10000 :slots 6 :seconds 2 :final-samples 1}
                             (fn [p] nil) (fn [] false)))
  (assert (= :heuristic (heuristic :search)))
  (assert (>= (get-in heuristic [:rows 0 :metrics :damage]) (get-in best [:metrics :damage]))
          "The time-limited search must discover the stronger AP combination.")
  # A very high-health target and attack-only strategies remain valid inputs;
  # no champion label forces an AP score or suppresses real AD damage.
  (def attack-input {"abilities" false})
  (def ap-attacks (scenario/fitness (definition champion ["3089" "3135" "6655"] attack-input)))
  (def ad-attacks (scenario/fitness (definition champion ["3153" "3046" "3087"] attack-input)))
  (assert (> (get-in ad-attacks [:metrics :damage]) (get-in ap-attacks [:metrics :damage])))
  (assert (= 10000 (get-in (definition champion [] {"targethealth" 10000}) [:target :hp]))))
(def fixed (definition "Ahri" [] {"targethealth" 10000}))
(assert (= 10000 (get (model/state-from-definition fixed) :target-health)))
(def text (ui/render (optimizer/controls {:state {}})))
(assert (string/find "Target health affects percentage-health damage" text))
(assert (string/find "$targethealth" text))
(util/remove-tree root)
(print "Retained mage kits: cached semantics, Viktor empowered attack/storm ticks, Ahri recasts, AP burst ranking, editable health and unbiased attack-only scores passed.")
