(import ../src/powerspike/scenario-wire :as wire)
(import ../src/powerspike/scenario :as scenario)
(import ../src/powerspike/calibration :as calibration)
(import ../src/powerspike/data-util :as util)
(import ../src/powerspike/engine :as engine)
(import ../web/model :as model)
(import ../web/catalog :as catalog)
(catalog/initialize "build/runtime-data" "build/seed")
(def state (model/parse-state {"champion" "Annie" "selected" "custom" "slot1" "1052" "level" 6 "mode" "duel"
                               "opponent" "Garen" "opponentlevel" 6 "samples" 8 "seed" 123 "distance" 400
                               "priority" "w,q,r,e,d,f" "opponentmovement" "hold-range" "opponentpreferredrange" 200 "qafter" 2}))
(def definition ((scenario/compile (model/definition state ["1052"])) :definition))
(def decoded (wire/decode (wire/encode definition)))
(assert (= (util/encode-data definition) (util/encode-data decoded)))
(def outcome (scenario/simulate decoded))
(def repeated (scenario/simulate decoded))
(assert (= (outcome :metrics) (repeated :metrics)))
(def restored (model/state-from-definition decoded))
(def round-trip (scenario/simulate (model/definition restored ["1052"])))
(assert (= (outcome :metrics) (round-trip :metrics)))
(def old (merge decoded {:model (string/repeat "0" 64)}))
(assert (some |(string/has-prefix? "This scenario was saved" $) ((scenario/compile old) :coverage)))
(assert (= (old :model) ((model/state-from-definition old) :savedmodel)))
(each bad ["{}" "(os/execute \"false\")" (string/repeat "x" 65537)
           (util/encode-json {:format "powerspike-scenario" :version 9 :scenario definition})
           (util/encode-json {:format "powerspike-scenario" :version 1 :scenario (merge definition {:execute "anything"})})
           (util/encode-json {:format "powerspike-scenario" :version 1 :scenario (merge definition {:snapshot (string/repeat "1" 64)})})]
  (assert (not (first (protect (wire/decode bad)))) "Unsafe or incompatible import should fail."))
(def record {"format" "powerspike-calibration" "version" 1 "family" "isolated-damage"})
(assert (= :unmeasured ((calibration/check record) :status)))
(def observation {"reviewed" true "value" (get-in outcome [:metrics :damage]) "metric" "damage" "tolerance" 0.00001
                  "required-source" "AnnieQ" "game-version" "test-fixture" "source" "synthetic regression; not an in-game capture"
                  "captured-at" "2026-10-05"})
(def checked (merge record {"observation" observation "scenario-document" (util/read-json (wire/encode definition))}))
(assert (= :consistent ((calibration/check checked) :status)))
(def absent (merge checked {"observation" (merge observation {"required-source" "unimplemented-effect" "value" 0})}))
(assert (= :unresolved ((calibration/check absent) :status)))
(assert (not ((calibration/check absent) :checked)))
(print "Scenario JSON, exact revisions, seeded reproduction, UI round trips, model compatibility, invalid imports and missing-measurement calibration passed.")
