(import ../data/16.19.1/snapshot :as snapshot)
(import ../data/16.19.1/annie :as annie)

(def evidence (parse (slurp ((dyn :args) 1))))
(defn compare-values [actual expected location]
  (cond
    (number? expected)
    (assert (and (number? actual) (< (math/abs (- actual expected)) 0.000001))
            (string "source mismatch: " location " expected=" expected " actual=" actual))
    (struct? expected)
    (eachp [key value] expected (compare-values (get actual key) value (string location "/" key)))
    (tuple? expected)
    (do (assert (= (length actual) (length expected)) (string "source length mismatch: " location))
      (eachp [index value] expected (compare-values (get actual index) value (string location "/" index))))
    (assert (= actual expected) (string "source mismatch: " location))))

(assert (= snapshot/patch (evidence :patch)) "snapshot patch mismatch")
(assert (= (length snapshot/champions) (length (evidence :champions))) "champion coverage mismatch")
(each expected (evidence :champions)
  (def champion (snapshot/champions (expected :id)))
  (compare-values champion expected (expected :id)))
(assert (= (length snapshot/items) (length (evidence :items))) "item coverage mismatch")
(each expected (evidence :items)
  (def item (snapshot/items (expected :id)))
  (compare-values item expected (expected :id))
  (assert (= (length (item :stats)) (length (expected :stats))) "item has unsourced normalized stats"))
(assert (= (length annie/spells) (length (evidence :abilities))) "ability coverage mismatch")
(eachp [index expected] (evidence :abilities)
  (compare-values (annie/spells index) expected (expected :id)))
(compare-values ((((snapshot/champions "Annie") :rank-penetration) :r) :magic-pen-percent)
                (evidence :annie-r-penetration) "Annie/R/penetration")
(assert (= (length snapshot/stat-shards) (length (evidence :stat-shards))) "stat shard coverage mismatch")
(each expected (evidence :stat-shards)
  (compare-values (snapshot/stat-shards (expected :id)) expected (string "stat-shard/" (expected :id))))
(print "Retained hashes, current spell references and normalized champion/item/spell/shard values verified.")
(print "This checks source interpretation; game timing, proc rules and build restrictions need separate evidence.")
