(import ./validation :as v)

(defn inspect-build [items options]
  (def slots (v/integer-between (get options :slots 6) 0 6 "slots"))
  (def budget (get options :budget math/inf))
  (when (not= budget math/inf) (v/nonnegative budget "budget"))
  (def map-id (get options :map 11))
  (def errors @[])
  (def seen @{})
  (def groups @{})
  (var cost 0)
  (when (> (length items) slots) (array/push errors "too many inventory slots"))
  (each item items
    (def id (item :id))
    (assert id "item requires an ID")
    (def gold (v/nonnegative (item :gold) "item gold"))
    (+= cost gold)
    (unless (item :supported) (array/push errors (string "unsupported item: " id)))
    (unless (item :purchasable) (array/push errors (string "not purchasable: " id)))
    (unless (some (fn [x] (= x map-id)) (item :maps))
      (array/push errors (string "not available on map: " id)))
    (when (and (seen id) (not (item :stackable)))
      (array/push errors (string "duplicate unique item: " id)))
    (put seen id true)
    (each group (get item :groups [])
      (when (groups group) (array/push errors (string "item group conflict: " group)))
      (put groups group true)))
  (when (> cost budget) (array/push errors "over budget"))
  {:legal (empty? errors) :errors (tuple ;errors) :cost cost})
