(import ./validation :as v)

(defn inspect-build [items options]
  (def slots (v/integer-between (get options :slots 6) 0 6 "slots"))
  (def budget (get options :budget math/inf))
  (when (not= budget math/inf) (v/nonnegative budget "budget"))
  (def map-id (get options :map 11))
  (def errors @[])
  (def seen @{})
  (def groups @{})
  (def capacities @{})
  (def owned (array/slice (get options :owned [])))
  (var cost 0)
  (when (> (length items) slots) (array/push errors "too many inventory slots"))
  (each item items
    (def id (item :id))
    (assert id "item requires an ID")
    (def gold (v/nonnegative (item :gold) "item gold"))
    (def owned-index (find-index |(= $ id) owned))
    (when owned-index (array/remove owned owned-index 1))
    (+= cost gold)
    (unless (item :supported) (array/push errors (string "unsupported item: " id)))
    (unless (or owned-index (item :purchasable)) (array/push errors (string "not purchasable: " id)))
    (unless (some (fn [x] (= x map-id)) (item :maps))
      (array/push errors (string "not available on map: " id)))
    (when (and (seen id) (not (item :stackable)))
      (array/push errors (string "duplicate unique item: " id)))
    (when (and (not= "" (get item :required-champion ""))
               (not= (item :required-champion) (get options :champion)))
      (array/push errors (string "champion restriction: " id)))
    (when (some |(= $ id) (get options :exclusions [])) (array/push errors (string "excluded item: " id)))
    (when (and (not owned-index) (has-key? item :in-store) (not (item :in-store))) (array/push errors (string "outside regular shop: " id)))
    (when (and (not owned-index) (= false (get-in item [:record "mItemDataAvailability" "mInStore"])))
      (array/push errors (string "unavailable in source shop rules: " id)))
    (when (and (not owned-index) (not= "" (get-in item [:record "mRequiredBuffCurrencyName"] "")))
      (array/push errors (string "requires an unmodeled purchase unlock: " id)))
    (when (some |(= "Trinket" $) (get item :tags (get-in item [:source "tags"] [])))
      (array/push errors (string "trinket occupies a separate slot: " id)))
    (when (and (not owned-index) (or (get-in item [:source "consumeOnFull"]) (get-in item [:source "hideFromAll"])))
      (array/push errors (string "special purchase or consumption rules unavailable: " id)))
    (put seen id true)
    (each group (get item :groups [])
      (def count (inc (get groups group 0)))
      (put groups group count)
      (put capacities group (min (get capacities group math/inf) (get-in item [:group-limits group] 1)))
      (when (> count (capacities group)) (array/push errors (string "item group conflict: " group)))))
  (when (> cost budget) (array/push errors "over budget"))
  {:legal (empty? errors) :errors (tuple ;errors) :cost cost})
