(import ./validation :as v)
(import ./damage :as damage)

# This is an explicit action evaluator, not an inferred champion combo.
# Targets are stationary and their resistance stays fixed throughout the window.
(defn simulate [stats target scenario]
  (def duration (v/nonnegative (scenario :duration) "duration"))
  (assert (> duration 0) "duration must be positive")
  (var resource (v/nonnegative (get scenario :resource (get stats :mp 0)) "resource"))
  (var busy-until 0)
  (var attack-ready 0)
  (def spell-ready @{})
  (def events @[])
  (def actions (sorted (scenario :actions) (fn [a b] (< (a :at) (b :at)))))
  (each action actions
    (def at (v/nonnegative (action :at) "action start"))
    (assert (< at duration) "action starts outside combat window")
    (assert (>= (+ at 1e-9) busy-until) "action overlaps another action's cast or windup")
    (var hit-time at)
    (var raw 0)
    (var type :physical)
    (var source :attack)
    (case (action :kind)
      :attack
      (do
        (def attack-speed (v/nonnegative (stats :attack-speed) "attack speed"))
        (assert (> attack-speed 0) "cannot attack with zero attack speed")
        (assert (>= (+ at 1e-9) attack-ready) "attack timer is not ready")
        # Timing is supplied by the scenario until champion windup calibration exists.
        (def windup (v/nonnegative (action :windup) "attack windup"))
        (assert (<= windup (/ 1 attack-speed)) "windup exceeds attack period")
        (set busy-until (+ at windup))
        (set attack-ready (+ at (/ 1 attack-speed)))
        (set hit-time (+ busy-until (v/nonnegative (get action :travel-time 0) "travel time")))
        (set raw (damage/expected-attack-damage stats)))
      :spell
      (do
        (def spell (action :spell))
        (assert (spell :id) "spell requires an ID")
        (def rank (action :rank))
        (v/integer-between rank 1 (length (spell :base-damage)) "spell rank")
        (defn ranked [key]
          (def values (spell key))
          (assert (= (length values) (length (spell :base-damage)))
                  (string "ranked spell field length mismatch: " key))
          (values (- rank 1)))
        (assert (>= (+ at 1e-9) (get spell-ready (spell :id) 0)) "spell is on cooldown")
        (def cost (v/nonnegative (ranked :cost) "spell cost"))
        (assert (>= resource cost) "insufficient resource")
        (-= resource cost)
        (def cast-time (v/nonnegative (spell :cast-time) "cast time"))
        (set busy-until (+ at cast-time))
        (def cd-start (spell :cooldown-start))
        (assert (or (= cd-start :start) (= cd-start :end)) "cooldown start must be explicit")
        (put spell-ready (spell :id)
             (+ (if (= cd-start :start) at busy-until)
                (damage/cooldown (ranked :cooldown) (get stats :ability-haste 0))))
        (set hit-time (+ busy-until (v/nonnegative (get action :travel-time 0) "travel time")))
        (set raw (damage/spell-damage spell rank stats))
        (set type (spell :damage-type))
        (set source (spell :id)))
      (error "unknown action kind"))
    # Half-open window: damage arriving exactly at duration is excluded.
    (when (< hit-time duration)
      (def resolved @{})
      (eachp [key value] (damage/resolve-hit raw type stats target) (put resolved key value))
      (put resolved :at hit-time)
      (put resolved :start at)
      (put resolved :source source)
      (array/push events resolved)))
  (def ordered (sorted events (fn [a b] (< (a :at) (b :at)))))
  (def total (reduce + 0 (map (fn [x] (x :damage)) ordered)))
  {:damage total :dps (/ total duration) :events ordered :resource-left resource
   :model :expected-damage :duration duration})

(defn auto-attacks [stats target scenario]
  (def duration (v/nonnegative (scenario :duration) "duration"))
  (assert (> duration 0) "duration must be positive")
  (def rate (v/nonnegative (stats :attack-speed) "attack speed"))
  (assert (> rate 0) "attack speed must be positive")
  (def windup-fraction (v/fraction (scenario :windup-fraction) "windup fraction"))
  (def travel-time (v/nonnegative (get scenario :travel-time 0) "travel time"))
  (def period (/ 1 rate))
  (def actions @[])
  (var index 0)
  (while (< (* index period) duration)
    (array/push actions {:at (* index period) :kind :attack
                         :windup (* windup-fraction period) :travel-time travel-time})
    (++ index))
  (simulate stats target {:duration duration :actions actions}))
