(import ./expressions :as expr)
(import ./damage :as damage)
(import ./data-util :as util)
(import pshash :as hash)

(def version "combat-2")
(def identity (hash/sha256 (string version (slurp "src/powerspike/engine.janet")
                                   (slurp "src/powerspike/expressions.janet") (slurp "src/powerspike/stats.janet")
                                   (slurp "src/powerspike/damage.janet") (slurp "src/powerspike/effects.janet")
                                   (slurp "src/powerspike/normalize.janet")
                                   (slurp "src/powerspike/tooltip.janet")
                                   (slurp "src/powerspike/objectives.janet")
                                   (slurp "src/powerspike/scenario.janet") (slurp "src/powerspike/skills.janet")
                                   (slurp "src/powerspike/builds.janet") (slurp "data/16.19.1/annie.janet")
                                   (slurp "data/semantic-overrides.jdn"))))
(defn less? [a b]
  (cond (not= (a :at) (b :at)) (< (a :at) (b :at))
    (not= (a :priority) (b :priority)) (< (a :priority) (b :priority))
    (< (a :sequence) (b :sequence))))
(defn push [heap event]
  (array/push heap event)
  (var i (dec (length heap)))
  (while (> i 0)
    (def parent (math/floor (/ (dec i) 2)))
    (unless (less? (heap i) (heap parent)) (break))
    (def value (heap parent)) (put heap parent (heap i)) (put heap i value) (set i parent)))
(defn pop [heap]
  (def event (heap 0))
  (def tail (array/pop heap))
  (unless (empty? heap)
    (put heap 0 tail)
    (var i 0)
    (forever
      (def left (+ (* i 2) 1))
      (when (>= left (length heap)) (break))
      (def right (inc left))
      (def child (if (and (< right (length heap)) (less? (heap right) (heap left))) right left))
      (unless (less? (heap child) (heap i)) (break))
      (def value (heap i)) (put heap i (heap child)) (put heap child value) (set i child)))
  event)
(defn random-at [seed trial actor kind index]
  (/ (scan-number (string "0x" (string/slice (hash/sha256 (string seed "/" trial "/" actor "/" kind "/" index)) 0 8))) 4294967296))
(defn state [actor index]
  (def stats (merge @{} (actor :stats)))
  (assert (and (util/finite? (stats :hp)) (> (stats :hp) 0)) "Actor needs positive maximum health.")
  (merge @{} actor {:index index :target (- 1 index) :stats stats :original-stats (merge {} stats)
                    :health (min (stats :hp) (get actor :health (stats :hp)))
                    :resource (min (get stats :mp 0) (get actor :resource (get stats :mp 0)))
                    :position (get actor :position 0) :velocity 0 :busy-until 0 :attack-ready 0
                    :ready @{} :charges @{} :recasts @{} :controls @{} :buffs @{} :buff-counts @{} :shields @[] :stat-effects @{}
                    :counters @{} :proc-ready @{} :proc-counts @{} :modifiers @[]
                    :damage-dealt 0 :attack-damage 0 :breakdown @{} :damage-taken 0 :healed 0 :absorbed 0 :control-time 0 :actions 0}))
(defn context [actor target rank]
  (def stats (merge @{} (actor :stats)
                    {:health (actor :health) :health-percent (/ (actor :health) ((actor :stats) :hp))
                     :missing-health (- ((actor :stats) :hp) (actor :health))
                     :missing-health-percent (- 1 (/ (actor :health) ((actor :stats) :hp)))}))
  {:stats stats :base (actor :base) :rank rank :level (actor :level) :buffs (actor :buff-counts)
   :ranged (get actor :ranged false)
   :target (merge (target :stats) {:health (target :health)
                                   :missing-health (- ((target :stats) :hp) (target :health))})})
(defn value [expression actor target rank]
  (if (number? expression) expression (expr/evaluate expression (context actor target rank))))
(defn alive? [actor] (not (actor :dead-at)))
(defn controlled? [actor controls at]
  (some |(> (get (actor :controls) $ 0) at) controls))
(defn target-allowed? [effect target]
  (and (or (not (effect :target-kinds))
           (some |(some (fn [kind] (= $ kind)) (get target :tags [(target :kind)])) (effect :target-kinds)))
       (not (some |(= $ (target :objective)) (get effect :exclude-objectives [])))))
(defn simulate [scenario &opt cancelled]
  (def duration (scenario :duration))
  (assert (and (util/finite? duration) (< 0 duration 180)) "Combat duration must be below 180 seconds.")
  (assert (= 2 (length (scenario :actors))) "This model supports exactly two participants.")
  (def actors (map state (scenario :actors) [0 1]))
  (def queue @[])
  (def trace @[])
  (def hits @[])
  (def unsupported @[])
  (def tracing (get scenario :trace true))
  (def seed (get scenario :seed 1))
  (def trial (get scenario :trial 0))
  (var sequence 0)
  (var at 0)
  (var processed 0)
  (var before nil)
  (def limit (min 100000 (get scenario :event-limit 10000)))
  (defn note [message]
    (unless (some |(= $ message) unsupported) (array/push unsupported message)))
  (defn schedule [time priority kind fields]
    (when (< time duration)
      (assert (and (util/finite? time) (>= time at)) "Invalid event timestamp.")
      (assert (< (length queue) (get scenario :pending-limit 20000)) "Pending event limit reached.")
      (++ sequence) (push queue (merge fields {:at time :priority priority :kind kind :sequence sequence}))))
  (defn refresh-stats [actor]
    (def totals (merge @{} (actor :original-stats)))
    (each modifier (values (actor :stat-effects))
      (when (> (modifier :expires) at)
        (def key (modifier :stat))
        (def before (get totals key (if (some |(= key $) [:outgoing-multiplier :healing-multiplier]) 1 0)))
        (put totals key (case (modifier :mode)
                          :multiply (* before (modifier :amount))
                          :maximum (max before (modifier :amount))
                          (+ before (modifier :amount))))))
    (put actor :stats totals)
    (put actor :health (min (actor :health) (totals :hp))))
  (defn participants []
    (map |{:id ($ :id) :health ($ :health) :resource ($ :resource) :position ($ :position)} actors))
  (defn record [kind fields]
    (when tracing
      (array/push trace (merge fields {:at at :kind kind :before before :participants (participants)}))))
  (defn advance [time]
    (def dt (- time at))
    (def positions (map |($ :position) actors))
    (each actor actors
      (when (alive? actor)
        (put actor :health (min ((actor :stats) :hp) (+ (actor :health) (* dt (/ (get (actor :stats) :hp-regen 0) 5) (get (actor :stats) :healing-multiplier 1)))))
        (put actor :resource (min (get (actor :stats) :mp 0) (+ (actor :resource) (* dt (/ (get (actor :stats) :mp-regen 0) 5)))))
        (def active (or (get-in actor [:strategy :attacks] false) (get-in actor [:strategy :abilities] false) (not= 0 (actor :velocity))))
        (def blocked (and active
                          (or (controlled? actor [:stun :charm :fear :airborne :suppression] at)
                              (and (not= 0 (actor :velocity)) (controlled? actor [:root] at))
                              (and (get-in actor [:strategy :abilities] false) (controlled? actor [:silence] at)))))
        (def impairment (cond blocked 1
                          (and (not= 0 (actor :velocity)) (controlled? actor [:slow] at)) (- 1 (get-in actor [:stat-effects :slow :amount] 1))
                          0))
        (put actor :control-time (+ (actor :control-time) (* dt impairment)))
        (unless (or (> (actor :busy-until) at) (controlled? actor [:stun :root :charm :fear :airborne :suppression] at))
          (def step (* dt (actor :velocity)))
          (def position (actor :position))
          (def enemy-position (positions (actor :target)))
          (put actor :position (if (< position enemy-position) (min (+ position step) enemy-position)
                                 (max (+ position step) enemy-position))))))
    (set at time))
  (defn trigger [owner target event-key origin depth &opt slot]
    (when (< depth 3)
      (each effect (get owner :triggers [])
        (def id (effect :id))
        (when (and (some |(= $ event-key) (get effect :on []))
                   (or (not (effect :ability-slots)) (some |(= $ slot) (effect :ability-slots)))
                   (<= (get (owner :proc-ready) id 0) at)
                   (or (not (effect :requires-buff)) (> (get (owner :buff-counts) (effect :requires-buff) 0) 0))
                   (target-allowed? effect target))
          (def result (protect
                        (def counter (get (owner :proc-counts) id @{:count 0 :last (- math/inf) :origins @[]}))
                        (def window (value (get effect :window 999) owner target 1))
                        (when (> (- at (get counter :first (- math/inf))) window) (put counter :count 0) (put counter :origins @[]))
                        (when (= 0 (counter :count)) (put counter :first at))
                        (unless (some |(= $ origin) (counter :origins))
                          (put counter :count (inc (counter :count))) (array/push (counter :origins) origin))
                        (put counter :last at) (put (owner :proc-counts) id counter)
                        (when (>= (counter :count) (value (get effect :every 1) owner target 1))
                          (put counter :count 0) (put counter :origins @[])
                          (when (effect :consume-buff) (put (owner :buff-counts) (effect :consume-buff) 0))
                          (put (owner :proc-ready) id (+ at (max 0.001 (value (get effect :cooldown 0) owner target 1))))
                          (schedule at 10 :effect {:actor (owner :index) :target (if (= :self (effect :target)) (owner :index) (target :index)) :effect effect :rank 1
                                                   :source id :origin origin :depth (inc depth)}))))
          (unless (first result) (note (string id ": " (result 1))))))))
  (defn apply-effect [event]
    (def owner (actors (event :actor)))
    (def target (actors (event :target)))
    (def effect (event :effect))
    (def rank (get event :rank 1))
    (def depth (get event :depth 0))
    (def source (event :source))
    (def blocked (and (target :spell-immune) (not= (owner :index) (target :index))
                      (not= :attack (get event :trigger)) (not (effect :affects-structures))))
    (def unknown-slow (and (= :control (effect :kind)) (= :slow (effect :control)) (not (effect :strength))))
    (when blocked (record :immune {:source source :target (target :id)}))
    (when unknown-slow (note (string source ": Slow strength unresolved; movement reduction and utility contribution excluded.")))
    (when (and (alive? target) (not= :unresolved (get effect :condition :always))
               (target-allowed? effect target) (not blocked) (not unknown-slow))
      (def outcome (protect
                     (case (effect :kind)
                       :damage
                       (do
                         (def raw (max 0 (value (effect :amount) owner target rank)))
                         (def capped (if (and (= :objective (target :kind)) (effect :monster-cap))
                                       (min raw (value (effect :monster-cap) owner target rank)) raw))
                         (def type (if (= :adaptive (effect :damage-type))
                                     (if (>= (get (owner :stats) :ap 0) (/ (get (owner :stats) :bonus-ad 0) 0.6)) :magic :physical)
                                     (effect :damage-type)))
                         (def outgoing (if (= :true type) 1 (get (owner :stats) :outgoing-multiplier 1)))
                         (def hit (damage/resolve-hit (* capped outgoing) type (owner :stats) (target :stats)))
                         (var remaining (* (hit :damage) (get target :damage-multiplier 1)))
                         (def before remaining)
                         (each shield (target :shields)
                           (when (and (> remaining 0) (> (shield :expires) at)
                                      (or (= :all (shield :type)) (= (hit :type) (shield :type))))
                             (def absorbed (min remaining (shield :amount)))
                             (-= remaining absorbed) (put shield :amount (- (shield :amount) absorbed))))
                         (def applied (min (target :health) remaining))
                         (put target :health (max 0 (- (target :health) remaining)))
                         (put target :absorbed (+ (target :absorbed) (- before remaining)))
                         (put target :damage-taken (+ (target :damage-taken) applied))
                         (put owner :damage-dealt (+ (owner :damage-dealt) applied))
                         (put (owner :breakdown) source (+ (get (owner :breakdown) source 0) applied))
                         (when (= "attack" source) (put owner :attack-damage (+ (owner :attack-damage) applied)))
                         (when tracing
                           (def summary (merge hit {:at at :source source :actor (owner :id) :target (target :id)
                                                    :damage applied :absorbed (- before remaining) :health (target :health)
                                                    :origin (event :origin)}))
                           (put summary :critical (get event :critical false))
                           (array/push hits summary)
                           (record :damage summary))
                         (when (<= (target :health) 0) (schedule at 20 :death {:actor (target :index)}))
                         # Proc damage does not recursively trigger other damage procs by default.
                         (when (= depth 0)
                           (trigger owner target (get event :trigger :spell-hit) (event :origin) depth (event :ability-slot))
                           (trigger owner target :damage (event :origin) depth)
                           (trigger target owner :damage-taken (event :origin) depth)))
                       :heal
                       (do (def amount (min (- ((target :stats) :hp) (target :health))
                                            (max 0 (* (value (effect :amount) owner target rank) (get (target :stats) :healing-multiplier 1)))))
                         (put target :health (+ (target :health) amount))
                         (put owner :healed (+ (owner :healed) amount)) (record :heal {:source source :amount amount :actor (owner :id)}))
                       :shield
                       (do (def amount (max 0 (value (effect :amount) owner target rank)))
                         (def expires (+ at (value (effect :duration) owner target rank)))
                         (array/push (target :shields) @{:amount amount :expires expires :type (get effect :shield-type :all)})
                         (schedule expires 0 :expire {:actor (target :index)})
                         (record :shield {:source source :amount amount :actor (owner :id)}))
                       :control
                       (unless (some |(= $ (effect :control)) (get target :immunities []))
                         (def length (* (max 0 (value (effect :duration) owner target rank))
                                        (if (some |(= $ (effect :control)) [:airborne :suppression]) 1
                                          (- 1 (max 0 (min 1 (get (target :stats) :tenacity 0)))))))
                         (put (target :controls) (effect :control) (max (get (target :controls) (effect :control) 0) (+ at length)))
                         (when (= :slow (effect :control))
                           (if (effect :strength)
                             (do (put (target :stat-effects) :slow {:stat :move-speed :mode :multiply
                                                                    :amount (- 1 (max 0 (min 1 (value (effect :strength) owner target rank))))
                                                                    :expires (+ at length)})
                               (refresh-stats target))
                             (note (string source ": Slow strength unresolved; movement reduction excluded."))))
                         (schedule (+ at length) 0 :expire {:actor (target :index)})
                         (record :control {:source source :control (effect :control) :duration length :target (target :id)}))
                       :buff
                       (do (put (target :buff-counts) (effect :buff) (if (effect :refresh) (get effect :stacks 1)
                                                                       (+ (get (target :buff-counts) (effect :buff) 0) (get effect :stacks 1))))
                         (def expires (+ at (value (effect :duration) owner target rank)))
                         (when (effect :refresh) (put (target :buffs) (effect :buff) expires))
                         (schedule (+ at (value (effect :duration) owner target rank)) 0 :buff-expire
                                   {:actor (target :index) :buff (effect :buff) :stacks (get effect :stacks 1) :refresh (effect :refresh) :expires expires})
                         (record :buff {:source source :buff (effect :buff) :target (target :id)}))
                       :stat-buff
                       (do (def amount (value (effect :amount) owner target rank))
                         (def expires (+ at (value (effect :duration) owner target rank)))
                         (def id (get effect :buff (tuple source (effect :stat))))
                         (put (target :stat-effects) id {:stat (effect :stat) :mode (get effect :mode :add)
                                                         :amount (if (effect :relative) (+ 1 amount) amount) :expires expires})
                         (refresh-stats target) (schedule expires 0 :expire {:actor (target :index)})
                         (record :stat-buff {:source source :stat (effect :stat) :amount amount :duration (- expires at) :target (target :id)}))
                       :cleanse
                       (do (each control (effect :controls) (put (target :controls) control at))
                         (put (target :stat-effects) :slow nil) (refresh-stats target)
                         (record :cleanse {:source source :target (target :id)}))
                       :reset (put owner :attack-ready at)
                       (note (string source ": Unsupported effect kind " (effect :kind))))))
      (unless (first outcome) (note (string source ": " (outcome 1))))))
  (defn permitted? [actor target ability]
    (def activation (get-in actor [:strategy :activation (ability :slot)] {}))
    (and (>= at (get activation :after 0))
         (<= (/ (actor :health) ((actor :stats) :hp)) (get activation :self-health-below 1))
         (<= (/ (target :health) ((target :stats) :hp)) (get activation :target-health-below 1))))
  (defn release-effect [event actor target ability effect travel]
    (if (or (= :unresolved (get effect :status)) (= :unresolved (get effect :condition)))
      (note (string (ability :id) ": " (get-in effect [:evidence :tooltip] "Unresolved effect")))
      (case (get effect :trigger :cast)
        :attack
        (do
          (def duration (effect :duration))
          (def count (if (has-key? effect :attack-count) (effect :attack-count) 1))
          (assert (or duration (not= count :all)) "Timed attack empowerment requires a duration.")
          (unless duration (note (string (ability :id) ": Empowerment expiry unavailable; retained until its attack count is consumed.")))
          (def window (when duration (value duration actor target (event :rank))))
          (when duration (assert (and (util/finite? window) (>= window 0)) "Empowered attack duration must be nonnegative."))
          (def expires (if duration (+ at window) math/inf))
          (def remaining (if (= count :all) math/inf (value count actor target (event :rank))))
          (assert (and (> remaining 0) (or (= remaining math/inf) (= remaining (math/floor remaining))))
                  "Empowered attack count must be a positive integer.")
          # Recasting refreshes this effect; separate abilities may coexist.
          (put actor :modifiers (filter |(not (and (= ($ :source) (ability :id))
                                                   (= (get-in $ [:effect :id]) (effect :id)))) (actor :modifiers)))
          (array/push (actor :modifiers) @{:effect effect :source (ability :id) :rank (event :rank)
                                           :remaining remaining :expires expires})
          (when (effect :reset) (put actor :attack-ready at)))
        :cast
        (do
          (def impact (+ at (* travel (get effect :travel-multiplier 1))
                         (value (get effect :delay 0) actor target (event :rank))))
          (def count (min 100 (max 1 (value (get effect :hits 1) actor target (event :rank)))))
          (def interval (value (get effect :interval 0) actor target (event :rank)))
          (for i 0 count
            (schedule (+ impact (* i interval)) 10 :effect
                      {:actor (actor :index) :target (if (= :self (effect :target)) (actor :index) (target :index))
                       :effect effect :rank (event :rank) :source (ability :id) :origin (event :origin) :ability-slot (ability :slot)})))
        (note (string (ability :id) ": Unsupported effect trigger")))))
  (defn release [event]
    (def actor (actors (event :actor)))
    (def target (actors (event :target)))
    (when (alive? actor)
      (def ability (event :ability))
      (def distance (math/abs (- (actor :position) (target :position))))
      (def speed (get ability :missile-speed (get actor :attack-missile-speed 0)))
      (def travel (if (> speed 0) (/ distance speed) 0))
      (def hit-chance (get-in actor [:strategy :hit-chance] 1))
      (cond
        (and (= :attack (event :action)) (controlled? actor [:stun :charm :fear :airborne :suppression] at))
        (record :interrupted {:source "attack" :actor (actor :id)})
        (and (or (= :attack (event :action)) (some |(= :enemy ($ :target)) (get ability :effects [])))
             (>= (random-at seed trial (actor :id) (event :source) (event :counter)) hit-chance))
        (record :miss {:source (event :source) :actor (actor :id)})
        (= :attack (event :action))
        (do
          (def critical (and (not (target :no-crit)) (< (random-at seed trial (actor :id) :crit (event :counter)) (get (actor :stats) :crit-chance 0))))
          (var raw (* (get (actor :stats) :ad 0) (if critical (get (actor :stats) :crit-damage 1.75) 1)))
          (when (actor :attack-ramp)
            (def ramp (actor :attack-ramp))
            (def stacks (if (> (- at (get actor :ramp-last (- math/inf))) (ramp :window)) 0 (get actor :ramp-stacks 0)))
            (*= raw (+ 1 (* stacks (ramp :step))))
            (put actor :ramp-last at) (put actor :ramp-stacks (min (ramp :maximum) (inc stacks))))
          (def modifiers (filter |(and (> ($ :expires) at) (> ($ :remaining) 0)) (actor :modifiers)))
          (def replacement (find |(and (= :damage (get-in $ [:effect :kind]))
                                       (= :replace (get-in $ [:effect :attack-mode] :replace))) modifiers))
          (unless replacement
            (schedule (+ at travel) 10 :effect {:actor (actor :index) :target (target :index)
                                                :effect {:kind :damage :damage-type :physical :amount raw :condition :always}
                                                :rank 1 :source "attack" :trigger :attack :origin (event :origin) :critical critical}))
          (each modifier modifiers
            (put modifier :remaining (dec (modifier :remaining)))
            (def effect (modifier :effect))
            (when (or (= modifier replacement) (not= :damage (effect :kind)) (= :bonus (get effect :attack-mode)))
              (schedule (+ at travel) 10 :effect {:actor (actor :index)
                                                  :target (if (= :self (effect :target)) (actor :index) (target :index)) :effect effect
                                                  :rank (modifier :rank) :source (modifier :source)
                                                  :trigger :attack :origin (event :origin)
                                                  :critical (and critical (= modifier replacement))}))))
        (and (get ability :channel false) (controlled? actor [:stun :charm :fear :airborne :suppression :silence] at))
        (record :interrupted {:source (ability :id) :actor (actor :id)})
        (each effect (ability :effects)
          (def released (protect (release-effect event actor target ability effect travel)))
          (unless (first released) (note (string (ability :id) ": " (released 1))))))))
  (defn decide [actor]
    (def target (actors (actor :target)))
    (when (and (alive? actor) (alive? target))
      (def strategy (get actor :strategy {}))
      (def distance (math/abs (- (actor :position) (target :position))))
      (def range (get actor :attack-range 125))
      (def movement (get strategy :movement :hold))
      (def desired (if (= :hold-range movement) (get strategy :preferred-range range) range))
      (def direction (if (< (actor :position) (target :position)) 1 -1))
      (put actor :velocity
           (cond (and (some |(= $ movement) [:approach :hold-range]) (> distance (+ desired (if (= :hold-range movement) 1 0))))
             (* direction (get (actor :stats) :move-speed 0))
             (and (= :hold-range movement) (< distance (- desired 1)))
             (* -1 direction (get (actor :stats) :move-speed 0))
             0))
      (var selected nil)
      (var rank 0)
      (var cost 0)
      (var cooldown 0)
      (var next (+ at 0.05))
      (when (and (<= (actor :busy-until) at)
                 (not (controlled? actor [:stun :charm :fear :airborne :suppression :silence] at))
                 (get strategy :abilities true))
        (each slot (get strategy :priority [:q :w :e :r])
          (unless selected
            (def ability (find |(= slot ($ :slot)) (get actor :abilities [])))
            (def learned (get (actor :ranks) slot 0))
            (def recast (when ability (get (actor :recasts) (ability :id))))
            (when (and ability (> learned 0)
                       (or (and recast (> (recast :expires) at) (> (recast :remaining) 0) (<= (recast :next) at))
                           (<= (get (actor :ready) (ability :id) 0) at))
                       (permitted? actor target ability)
                       (some |(= :estimated ($ :status)) (ability :effects)))
              (def result (protect
                            (def cast-time (get ability :cast-time 0.25))
                            (assert (not= :unresolved (ability :cost-resource)) "Resource cost semantics require a handler.")
                            (assert (and (util/finite? cast-time) (<= 0 cast-time 10)) "Cast timing directive requires a handler.")
                            (def recasting (and recast (> (recast :expires) at) (> (recast :remaining) 0)))
                            (def resource-cost (if recasting (get-in ability [:recast :cost] 0) (max 0 (value (ability :cost) actor target learned))))
                            (def ability-range (max 0 (value (ability :range) actor target learned)))
                            (def cd (damage/cooldown (max 0 (value (ability :cooldown) actor target learned))
                                                     (if (ability :unhasted) 0 (get (actor :stats) :ability-haste 0))))
                            # A zero cooldown often represents a stack-gated
                            # activation, toggle or transformation. Repeatedly
                            # casting it would suppress every ordinary attack.
                            (assert (or (> cd 0) recasting (ability :max-charges))
                                    "Zero-cooldown activation requires a charge, recast or champion handler; effect excluded.")
                            (when (ability :max-charges)
                              (unless ((actor :charges) (ability :id))
                                (def maximum (value (ability :max-charges) actor target learned))
                                (assert (<= 1 maximum 10) "Invalid charge count.")
                                (put (actor :charges) (ability :id) @{:available maximum :maximum maximum :recovering false})))
                            (def charged (get (actor :charges) (ability :id)))
                            (def self-only (not (some |(and (= :enemy ($ :target)) (not= :attack (get $ :trigger))) (ability :effects))))
                            (def blocked (and (target :spell-immune) (not self-only)
                                              (not (some |($ :affects-structures) (ability :effects)))))
                            (when blocked (note (string (ability :id) ": Target is immune to this ability.")))
                            (def pool (if (= :health (get ability :cost-resource)) (actor :health) (actor :resource)))
                            (when (and (not blocked) (or self-only (<= distance ability-range)) (>= pool (+ resource-cost (if (= :health (ability :cost-resource)) 1 0)))
                                       (or (not charged) (> (charged :available) 0)))
                              (set selected ability) (set rank learned) (set cost resource-cost) (set cooldown cd))))
              (unless (first result) (note (string (ability :id) ": " (result 1))))))))
      (cond
        selected
        (do
          (def cast-time (get selected :cast-time 0.25))
          (assert (and (util/finite? cast-time) (<= 0 cast-time 10)) "Unsupported cast time.")
          (def counter (get (actor :counters) (selected :id) 0))
          (put (actor :counters) (selected :id) (inc counter))
          (put actor :actions (inc (actor :actions)))
          (def resource-key (if (= :health (selected :cost-resource)) :health :resource))
          (put actor resource-key (- (actor resource-key) cost))
          (put actor :busy-until (+ at cast-time))
          (def charged ((actor :charges) (selected :id)))
          (def recast ((actor :recasts) (selected :id)))
          (cond
            charged
            (do (put charged :available (dec (charged :available)))
              (def recharge (if (selected :recharge-time)
                              (damage/cooldown (value (selected :recharge-time) actor target rank)
                                               (if (selected :recharge-unhasted) 0 (get (actor :stats) :ability-haste 0)))
                              cooldown))
              (assert (> recharge 0) "Charge recharge time unavailable.")
              (unless (charged :recovering)
                (put charged :recovering true)
                (schedule (+ at recharge) 0 :charge {:actor (actor :index) :id (selected :id) :cooldown recharge}))
              (put (actor :ready) (selected :id) (+ at (max 0.05 (value (get selected :charge-delay cooldown) actor target rank)))))
            (and recast (> (recast :expires) at) (> (recast :remaining) 0))
            (do (put recast :remaining (dec (recast :remaining)))
              (put recast :next (+ at (value (get-in selected [:recast :delay] 0.1) actor target rank))))
            (do
              (put (actor :ready) (selected :id) (+ at (if (= :end (get selected :cooldown-start :start)) cast-time 0) (max 0.05 cooldown)))
              (when (selected :recast)
                (def expires (+ at (value (get-in selected [:recast :window]) actor target rank)))
                (def count (value (get-in selected [:recast :count] 1) actor target rank))
                (assert (and (= count (math/floor count)) (<= 0 count 10)) "Invalid recast count.")
                (put (actor :recasts) (selected :id) @{:remaining count
                                                       :next (+ at (value (get-in selected [:recast :delay] 0.1) actor target rank)) :expires expires}))))
          (record :cast {:actor (actor :id) :source (selected :id) :rank rank :cost cost :cooldown cooldown})
          (def origin (string (actor :id) "/" (selected :id) "/" counter))
          (unless (selected :unhasted) (trigger actor target :cast origin 0))
          (schedule (+ at cast-time) 5 :release {:actor (actor :index) :target (target :index) :ability selected
                                                 :rank rank :action :spell :source (selected :id) :counter counter :origin origin})
          (set next (max (+ at 0.01) (actor :busy-until))))
        (and (<= (actor :busy-until) at) (<= (actor :attack-ready) at)
             (<= distance range) (get strategy :attacks true)
             (not (controlled? actor [:stun :charm :fear :airborne :suppression] at))
             (> (get (actor :stats) :attack-speed 0) 0))
        (do
          (def period (/ 1 ((actor :stats) :attack-speed)))
          (def windup (* period (get actor :windup-fraction 0.3)))
          (def counter (get (actor :counters) :attack 0))
          (put (actor :counters) :attack (inc counter))
          (put actor :actions (inc (actor :actions)))
          (put actor :busy-until (+ at windup)) (put actor :attack-ready (+ at period))
          (record :attack {:actor (actor :id) :source "attack"})
          (schedule (+ at windup) 5 :release {:actor (actor :index) :target (target :index) :action :attack :source "attack"
                                              :counter counter :origin (string (actor :id) "/attack/" counter)})
          (set next (max (+ at 0.01) (actor :busy-until)))))
      (schedule next 30 :decide {:actor (actor :index)})))
  (record :start {})
  (each actor actors (schedule 0 30 :decide {:actor (actor :index)}))
  (each event (get scenario :initial-events []) (schedule (event :at) (get event :priority 10) (event :kind) event))
  (while (not (empty? queue))
    (++ processed)
    (assert (<= processed limit) "Combat event limit reached.")
    (when (and cancelled (= 0 (% processed 32)) (cancelled)) (error "Cancelled."))
    (def event (pop queue))
    (advance (event :at))
    (when tracing (set before (participants)))
    (case (event :kind)
      :decide (decide (actors (event :actor)))
      :release (release event)
      :effect (apply-effect event)
      :death (let [actor (actors (event :actor))]
               (when (and (alive? actor) (<= (actor :health) 0))
                 (put actor :dead-at at) (put actor :velocity 0)
                 (record :death {:actor (actor :id)})
                 (trigger (actors (actor :target)) actor :kill (string "death/" (actor :id)) 0)))
      :buff-expire (let [actor (actors (event :actor))]
                     (when (or (not (event :refresh)) (= (event :expires) ((actor :buffs) (event :buff))))
                       (put (actor :buff-counts) (event :buff) (max 0 (- (get (actor :buff-counts) (event :buff) 0) (event :stacks))))))
      :charge (let [actor (actors (event :actor)) charged ((actor :charges) (event :id))]
                (put charged :available (min (charged :maximum) (inc (charged :available))))
                (if (< (charged :available) (charged :maximum))
                  (schedule (+ at (event :cooldown)) 0 :charge event)
                  (put charged :recovering false))
                (record :charge {:actor (actor :id) :source (event :id) :charges (charged :available)}))
      :expire (do (refresh-stats (actors (event :actor))) (record :expire {:actor ((actors (event :actor)) :id)}))
      (note (string "Unsupported event: " (event :kind)))))
  (advance duration)
  (when tracing (set before (participants)))
  (record :end {})
  (def player (actors 0))
  (def opponent (actors 1))
  (def attack-damage (player :attack-damage))
  {:engine version :model identity :actors actors :trace trace :damage-breakdown (table/to-struct (player :breakdown))
   :events (filter |(= (player :id) ($ :actor)) hits) :unsupported unsupported
   :assumptions ["Declared ability priority precedes basic attacks."
                 "Cooldowns start on cast unless an override declares otherwise."
                 "Ordinary attack windup is 30% unless configured."
                 "Projectile travel uses distance at release; collision geometry is omitted."
                 "Ability resource costs use the participant's configured resource pool."
                 "Parsed effects are estimates; unresolved effects are excluded and reported."
                 "Damage triggers follow the initiating damage; exact game proc ordering remains unvalidated."]
   :damage (player :damage-dealt) :dps (/ (player :damage-dealt) duration)
   :attack-dps (/ attack-damage duration) :ability-dps (/ (- (player :damage-dealt) attack-damage) duration)
   :resource-left (player :resource)
   :metrics {:damage (player :damage-dealt) :attack-damage attack-damage :resource (player :resource)
             :damage-taken (player :damage-taken) :health (player :health)
             :healing (player :healed) :absorbed (player :absorbed) :control (opponent :control-time)
             :kill-time (opponent :dead-at) :death-time (player :dead-at)}})

(defn trials [scenario samples &opt cancelled]
  (assert (and (number? samples) (= samples (math/floor samples)) (<= 1 samples 256)) "Trial count must be from 1 to 256.")
  (def totals @{})
  (def squared @{})
  (def sources @{})
  (var representative nil)
  (var kills 0)
  (var deaths 0)
  (var wins 0)
  (var kill-sum 0)
  (var death-sum 0)
  (def omissions @[])
  (for trial 0 samples
    (when (and cancelled (cancelled)) (error "Cancelled."))
    (def result (simulate (merge scenario {:trial trial :trace (and (get scenario :trace true) (= trial 0))}) cancelled))
    (unless representative (set representative result))
    (eachp [source damage] (result :damage-breakdown) (put sources source (+ (get sources source 0) damage)))
    (each message (result :unsupported) (unless (some |(= $ message) omissions) (array/push omissions message)))
    (def metrics (result :metrics))
    (when (metrics :kill-time) (++ kills) (+= kill-sum (metrics :kill-time)))
    (when (metrics :death-time) (++ deaths) (+= death-sum (metrics :death-time)))
    (when (and (metrics :kill-time) (or (not (metrics :death-time)) (< (metrics :kill-time) (metrics :death-time)))) (++ wins))
    (each key [:damage :attack-damage :resource :damage-taken :health :healing :absorbed :control]
      (def value (get metrics key 0))
      (put totals key (+ (get totals key 0) value))
      (put squared key (+ (get squared key 0) (* value value)))))
  (def means (tabseq [[key total] :pairs totals] key (/ total samples)))
  (def uncertainty (tabseq [[key mean] :pairs means]
                     key (if (> samples 1)
                           (* 1.96 (math/sqrt (/ (max 0 (- (squared key) (* samples mean mean))) (* samples (dec samples))))) nil)))
  (merge representative {:unsupported omissions :samples samples :uncertainty uncertainty
                         :damage-breakdown (table/to-struct (tabseq [[source total] :pairs sources] source (/ total samples)))
                         :damage (means :damage) :dps (/ (means :damage) (scenario :duration)) :resource-left (means :resource)
                         :attack-dps (/ (means :attack-damage) (scenario :duration))
                         :ability-dps (/ (- (means :damage) (means :attack-damage)) (scenario :duration))
                         :metrics (table/to-struct (merge means {:win-rate (/ wins samples) :kill-rate (/ kills samples) :death-rate (/ deaths samples)
                                                                 :mean-kill-time (when (> kills 0) (/ kill-sum kills))
                                                                 :mean-death-time (when (> deaths 0) (/ death-sum deaths))}))
                         :sampling-note (if (= samples 1) "One seeded trial; sampling uncertainty unavailable."
                                          "Mean outcomes with approximate 95% sampling intervals; trace shows trial zero. Times average successful events only.")}))
