(import ./expressions :as expr)
(import ./damage :as damage)
(import ./data-util :as util)
(import pshash :as hash)

(def version "combat-1")
(def identity (hash/sha256 (string version (slurp "src/powerspike/engine.janet")
                                   (slurp "src/powerspike/expressions.janet") (slurp "src/powerspike/stats.janet")
                                   (slurp "src/powerspike/damage.janet") (slurp "data/semantic-overrides.jdn"))))
(defn less? [a b]
  (cond (not= (a :at) (b :at)) (< (a :at) (b :at))
    (not= (a :priority) (b :priority)) (< (a :priority) (b :priority))
    (< (a :sequence) (b :sequence))))
(defn push [heap event]
  (array/push heap event)
  (var i (dec (length heap)))
  (while (> i 0)
    (def parent (math/floor (/ (dec i) 2)))
    (unless (less? (heap i) (heap parent)) (break))
    (def value (heap parent)) (put heap parent (heap i)) (put heap i value) (set i parent)))
(defn pop [heap]
  (def event (heap 0))
  (def tail (array/pop heap))
  (unless (empty? heap)
    (put heap 0 tail)
    (var i 0)
    (forever
      (def left (+ (* i 2) 1))
      (when (>= left (length heap)) (break))
      (def right (inc left))
      (def child (if (and (< right (length heap)) (less? (heap right) (heap left))) right left))
      (unless (less? (heap child) (heap i)) (break))
      (def value (heap i)) (put heap i (heap child)) (put heap child value) (set i child)))
  event)
(defn random-at [seed trial actor kind index]
  (/ (scan-number (string "0x" (string/slice (hash/sha256 (string seed "/" trial "/" actor "/" kind "/" index)) 0 8))) 4294967296))
(defn state [actor index]
  (def stats (merge @{} (actor :stats)))
  (assert (and (util/finite? (stats :hp)) (> (stats :hp) 0)) "Actor needs positive maximum health.")
  (merge @{} actor {:index index :target (- 1 index) :stats stats :original-stats (merge {} stats)
                    :health (min (stats :hp) (get actor :health (stats :hp)))
                    :resource (min (get stats :mp 0) (get actor :resource (get stats :mp 0)))
                    :position (get actor :position 0) :velocity 0 :busy-until 0 :attack-ready 0
                    :ready @{} :charges @{} :controls @{} :buffs @{} :buff-counts @{} :shields @[]
                    :counters @{} :proc-ready @{} :proc-counts @{} :modifiers @[]
                    :damage-dealt 0 :attack-damage 0 :damage-taken 0 :healed 0 :absorbed 0 :control-time 0 :actions 0}))
(defn context [actor target rank]
  (def stats (merge @{} (actor :stats)
                    {:health (actor :health) :health-percent (/ (actor :health) ((actor :stats) :hp))
                     :missing-health (- ((actor :stats) :hp) (actor :health))
                     :missing-health-percent (- 1 (/ (actor :health) ((actor :stats) :hp)))}))
  {:stats stats :base (actor :base) :rank rank :level (actor :level) :buffs (actor :buff-counts)
   :ranged (get actor :ranged false)
   :target (merge (target :stats) {:health (target :health)
                                   :missing-health (- ((target :stats) :hp) (target :health))})})
(defn value [expression actor target rank]
  (if (number? expression) expression (expr/evaluate expression (context actor target rank))))
(defn alive? [actor] (not (actor :dead-at)))
(defn controlled? [actor controls at]
  (some |(> (get (actor :controls) $ 0) at) controls))
(defn simulate [scenario &opt cancelled]
  (def duration (scenario :duration))
  (assert (and (util/finite? duration) (< 0 duration 180)) "Combat duration must be below 180 seconds.")
  (assert (= 2 (length (scenario :actors))) "This model supports exactly two participants.")
  (def actors (map state (scenario :actors) [0 1]))
  (def queue @[])
  (def trace @[])
  (def hits @[])
  (def unsupported @[])
  (def tracing (get scenario :trace true))
  (def seed (get scenario :seed 1))
  (def trial (get scenario :trial 0))
  (var sequence 0)
  (var at 0)
  (var processed 0)
  (def limit (min 100000 (get scenario :event-limit 10000)))
  (defn note [message]
    (unless (some |(= $ message) unsupported) (array/push unsupported message)))
  (defn schedule [time priority kind fields]
    (when (< time duration)
      (assert (and (util/finite? time) (>= time at)) "Invalid event timestamp.")
      (++ sequence) (push queue (merge fields {:at time :priority priority :kind kind :sequence sequence}))))
  (defn record [kind fields]
    (when tracing
      (array/push trace (merge fields {:at at :kind kind
                                       :participants (map |{:id ($ :id) :health ($ :health) :resource ($ :resource)
                                                            :position ($ :position)} actors)}))))
  (defn advance [time]
    (def dt (- time at))
    (def positions (map |($ :position) actors))
    (each actor actors
      (when (alive? actor)
        (put actor :health (min ((actor :stats) :hp) (+ (actor :health) (* dt (/ (get (actor :stats) :hp-regen 0) 5)))))
        (put actor :resource (min (get (actor :stats) :mp 0) (+ (actor :resource) (* dt (/ (get (actor :stats) :mp-regen 0) 5)))))
        (when (controlled? actor [:stun :root :charm :fear :airborne :silence :slow] at)
          (put actor :control-time (+ (actor :control-time) dt)))
        (unless (or (> (actor :busy-until) at) (controlled? actor [:stun :root :charm :fear :airborne] at))
          (def step (* dt (actor :velocity)))
          (def position (actor :position))
          (def enemy-position (positions (actor :target)))
          (put actor :position (if (< position enemy-position) (min (+ position step) enemy-position)
                                 (max (+ position step) enemy-position))))))
    (set at time))
  (defn trigger [owner target event-key origin depth]
    (when (< depth 3)
      (each effect (get owner :triggers [])
        (def id (effect :id))
        (when (and (some |(= $ event-key) (get effect :on []))
                   (<= (get (owner :proc-ready) id 0) at)
                   (or (not (effect :target-kinds)) (some |(= $ (target :kind)) (effect :target-kinds))))
          (def result (protect
                        (def counter (get (owner :proc-counts) id @{:count 0 :last (- math/inf) :origins @[]}))
                        (def window (value (get effect :window 999) owner target 1))
                        (when (> (- at (counter :last)) window) (put counter :count 0) (put counter :origins @[]))
                        (unless (some |(= $ origin) (counter :origins))
                          (put counter :count (inc (counter :count))) (array/push (counter :origins) origin))
                        (put counter :last at) (put (owner :proc-counts) id counter)
                        (when (>= (counter :count) (value (get effect :every 1) owner target 1))
                          (put counter :count 0) (put counter :origins @[])
                          (put (owner :proc-ready) id (+ at (max 0.001 (value (get effect :cooldown 0) owner target 1))))
                          (schedule at 10 :effect {:actor (owner :index) :target (if (= :self (effect :target)) (owner :index) (target :index)) :effect effect :rank 1
                                                   :source id :origin origin :depth (inc depth)}))))
          (unless (first result) (note (string id ": " (result 1))))))))
  (defn apply-effect [event]
    (def owner (actors (event :actor)))
    (def target (actors (event :target)))
    (def effect (event :effect))
    (def rank (get event :rank 1))
    (def depth (get event :depth 0))
    (def source (event :source))
    (when (and (alive? target) (not= :unresolved (get effect :condition :always)))
      (def outcome (protect
                     (case (effect :kind)
                       :damage
                       (do
                         (def raw (max 0 (value (effect :amount) owner target rank)))
                         (def capped (if (and (= :objective (target :kind)) (number? (effect :monster-cap)))
                                       (min raw (effect :monster-cap)) raw))
                         (def hit (damage/resolve-hit capped (effect :damage-type) (owner :stats) (target :stats)))
                         (var remaining (* (hit :damage) (get target :damage-multiplier 1)))
                         (def before remaining)
                         (each shield (target :shields)
                           (when (and (> remaining 0) (> (shield :expires) at)
                                      (or (= :all (shield :type)) (= (hit :type) (shield :type))))
                             (def absorbed (min remaining (shield :amount)))
                             (-= remaining absorbed) (put shield :amount (- (shield :amount) absorbed))))
                         (def applied (min (target :health) remaining))
                         (put target :health (max 0 (- (target :health) remaining)))
                         (put target :absorbed (+ (target :absorbed) (- before remaining)))
                         (put target :damage-taken (+ (target :damage-taken) applied))
                         (put owner :damage-dealt (+ (owner :damage-dealt) applied))
                         (when (= "attack" source) (put owner :attack-damage (+ (owner :attack-damage) applied)))
                         (def summary (merge hit {:at at :source source :actor (owner :id) :target (target :id)
                                                  :damage applied :absorbed (- before remaining) :health (target :health)
                                                  :origin (event :origin)}))
                         (when tracing (array/push hits summary))
                         (record :damage summary)
                         (when (<= (target :health) 0) (schedule at 20 :death {:actor (target :index)}))
                         # Proc damage does not recursively trigger other damage procs by default.
                         (when (= depth 0)
                           (trigger owner target (get event :trigger :spell-hit) (event :origin) depth)
                           (trigger owner target :damage (event :origin) depth)
                           (trigger target owner :damage-taken (event :origin) depth)))
                       :heal
                       (do (def amount (min (- ((target :stats) :hp) (target :health))
                                            (max 0 (* (value (effect :amount) owner target rank) (get target :healing-multiplier 1)))))
                         (put target :health (+ (target :health) amount))
                         (put owner :healed (+ (owner :healed) amount)) (record :heal {:source source :amount amount :actor (owner :id)}))
                       :shield
                       (do (def amount (max 0 (value (effect :amount) owner target rank)))
                         (def expires (+ at (value (effect :duration) owner target rank)))
                         (array/push (target :shields) @{:amount amount :expires expires :type (get effect :shield-type :all)})
                         (schedule expires 0 :expire {:actor (target :index)})
                         (record :shield {:source source :amount amount :actor (owner :id)}))
                       :control
                       (unless (some |(= $ (effect :control)) (get target :immunities []))
                         (def length (* (max 0 (value (effect :duration) owner target rank)) (- 1 (get (target :stats) :tenacity 0))))
                         (put (target :controls) (effect :control) (max (get (target :controls) (effect :control) 0) (+ at length)))
                         (schedule (+ at length) 0 :expire {:actor (target :index)})
                         (record :control {:source source :control (effect :control) :duration length :target (target :id)}))
                       :buff
                       (do (put (target :buff-counts) (effect :buff) (+ (get (target :buff-counts) (effect :buff) 0) (get effect :stacks 1)))
                         (schedule (+ at (value (effect :duration) owner target rank)) 0 :buff-expire
                                   {:actor (target :index) :buff (effect :buff) :stacks (get effect :stacks 1)})
                         (record :buff {:source source :buff (effect :buff) :target (target :id)}))
                       :reset (put owner :attack-ready at)
                       (note (string source ": Unsupported effect kind " (effect :kind))))))
      (unless (first outcome) (note (string source ": " (outcome 1))))))
  (defn permitted? [actor target ability]
    (def activation (get-in actor [:strategy :activation (ability :slot)] {}))
    (and (>= at (get activation :after 0))
         (<= (/ (actor :health) ((actor :stats) :hp)) (get activation :self-health-below 1))
         (<= (/ (target :health) ((target :stats) :hp)) (get activation :target-health-below 1))))
  (defn release-effect [event actor target ability effect travel]
    (if (or (= :unresolved (get effect :status)) (= :unresolved (get effect :condition)))
      (note (string (ability :id) ": " (get-in effect [:evidence :tooltip] "Unresolved effect")))
      (case (get effect :trigger :cast)
        :attack
        (do
          (array/push (actor :modifiers) @{:effect effect :source (ability :id) :rank (event :rank)
                                           :remaining 1 :expires (+ at (value (effect :duration) actor target (event :rank)))})
          (when (effect :reset) (put actor :attack-ready at)))
        :cast
        (do
          (def impact (+ at (* travel (get effect :travel-multiplier 1))))
          (def count (min 100 (max 1 (value (get effect :hits 1) actor target (event :rank)))))
          (def interval (value (get effect :interval 0) actor target (event :rank)))
          (for i 0 count
            (schedule (+ impact (* i interval)) 10 :effect
                      {:actor (actor :index) :target (if (= :self (effect :target)) (actor :index) (target :index))
                       :effect effect :rank (event :rank) :source (ability :id) :origin (event :origin)})))
        (note (string (ability :id) ": Unsupported effect trigger")))))
  (defn release [event]
    (def actor (actors (event :actor)))
    (def target (actors (event :target)))
    (when (alive? actor)
      (def ability (event :ability))
      (def distance (math/abs (- (actor :position) (target :position))))
      (def speed (get ability :missile-speed (get actor :attack-missile-speed 0)))
      (def travel (if (> speed 0) (/ distance speed) 0))
      (def hit-chance (get-in actor [:strategy :hit-chance] 1))
      (cond
        (and (= :attack (event :action)) (controlled? actor [:stun :charm :fear :airborne] at))
        (record :interrupted {:source "attack" :actor (actor :id)})
        (>= (random-at seed trial (actor :id) (event :source) (event :counter)) hit-chance)
        (record :miss {:source (event :source) :actor (actor :id)})
        (= :attack (event :action))
        (do
          (def critical (< (random-at seed trial (actor :id) :crit (event :counter)) (get (actor :stats) :crit-chance 0)))
          (def raw (* (get (actor :stats) :ad 0) (if critical (get (actor :stats) :crit-damage 1.75) 1)))
          (def modifier (find |(and (> ($ :expires) at) (> ($ :remaining) 0)) (actor :modifiers)))
          (when modifier (put modifier :remaining (dec (modifier :remaining))))
          (def effects (if modifier [(modifier :effect)] [{:kind :damage :damage-type :physical :amount raw :condition :always}]))
          (each effect effects
            (schedule (+ at travel) 10 :effect {:actor (actor :index) :target (target :index) :effect effect
                                                :rank (get modifier :rank 1) :source (get modifier :source "attack")
                                                :trigger :attack :origin (event :origin) :critical critical})))
        (and (get ability :channel false) (controlled? actor [:stun :charm :fear :airborne :silence] at))
        (record :interrupted {:source (ability :id) :actor (actor :id)})
        (each effect (ability :effects)
          (def released (protect (release-effect event actor target ability effect travel)))
          (unless (first released) (note (string (ability :id) ": " (released 1))))))))
  (defn decide [actor]
    (def target (actors (actor :target)))
    (when (and (alive? actor) (alive? target))
      (def strategy (get actor :strategy {}))
      (def distance (math/abs (- (actor :position) (target :position))))
      (def range (get actor :attack-range 125))
      (put actor :velocity
           (if (and (= :approach (get strategy :movement :hold)) (> distance range))
             (* (if (< (actor :position) (target :position)) 1 -1) (get (actor :stats) :move-speed 0)) 0))
      (var selected nil)
      (var rank 0)
      (var cost 0)
      (var cooldown 0)
      (var next (+ at 0.05))
      (when (and (<= (actor :busy-until) at)
                 (not (controlled? actor [:stun :charm :fear :airborne :silence] at))
                 (get strategy :abilities true))
        (each slot (get strategy :priority [:q :w :e :r])
          (unless selected
            (def ability (find |(= slot ($ :slot)) (get actor :abilities [])))
            (def learned (get (actor :ranks) slot 0))
            (when (and ability (> learned 0) (<= (get (actor :ready) (ability :id) 0) at)
                       (permitted? actor target ability)
                       (some |(= :estimated ($ :status)) (ability :effects)))
              (def result (protect
                            (def cast-time (get ability :cast-time 0.25))
                            (assert (and (util/finite? cast-time) (<= 0 cast-time 10)) "Cast timing directive requires a handler.")
                            (def resource-cost (max 0 (value (ability :cost) actor target learned)))
                            (def ability-range (max 0 (value (ability :range) actor target learned)))
                            (def cd (damage/cooldown (max 0 (value (ability :cooldown) actor target learned)) (get (actor :stats) :ability-haste 0)))
                            (def self-only (not (some |(= :enemy ($ :target)) (ability :effects))))
                            (when (and (or self-only (<= distance ability-range)) (>= (actor :resource) resource-cost))
                              (set selected ability) (set rank learned) (set cost resource-cost) (set cooldown cd))))
              (unless (first result) (note (string (ability :id) ": " (result 1))))))))
      (cond
        selected
        (do
          (def cast-time (get selected :cast-time 0.25))
          (assert (and (util/finite? cast-time) (<= 0 cast-time 10)) "Unsupported cast time.")
          (def counter (get (actor :counters) (selected :id) 0))
          (put (actor :counters) (selected :id) (inc counter))
          (put actor :actions (inc (actor :actions)))
          (put actor :resource (- (actor :resource) cost))
          (put actor :busy-until (+ at cast-time))
          (put (actor :ready) (selected :id) (+ at (if (= :end (get selected :cooldown-start :start)) cast-time 0) (max 0.05 cooldown)))
          (record :cast {:actor (actor :id) :source (selected :id) :rank rank :cost cost :cooldown cooldown})
          (def origin (string (actor :id) "/" (selected :id) "/" counter))
          (trigger actor target :cast origin 0)
          (schedule (+ at cast-time) 5 :release {:actor (actor :index) :target (target :index) :ability selected
                                                 :rank rank :action :spell :source (selected :id) :counter counter :origin origin})
          (set next (max (+ at 0.01) (actor :busy-until))))
        (and (<= (actor :busy-until) at) (<= (actor :attack-ready) at)
             (<= distance range) (get strategy :attacks true)
             (not (controlled? actor [:stun :charm :fear :airborne] at))
             (> (get (actor :stats) :attack-speed 0) 0))
        (do
          (def period (/ 1 ((actor :stats) :attack-speed)))
          (def windup (* period (get actor :windup-fraction 0.3)))
          (def counter (get (actor :counters) :attack 0))
          (put (actor :counters) :attack (inc counter))
          (put actor :actions (inc (actor :actions)))
          (put actor :busy-until (+ at windup)) (put actor :attack-ready (+ at period))
          (record :attack {:actor (actor :id) :source "attack"})
          (schedule (+ at windup) 5 :release {:actor (actor :index) :target (target :index) :action :attack :source "attack"
                                              :counter counter :origin (string (actor :id) "/attack/" counter)})
          (set next (max (+ at 0.01) (actor :busy-until)))))
      (schedule next 30 :decide {:actor (actor :index)})))
  (record :start {})
  (each actor actors (schedule 0 30 :decide {:actor (actor :index)}))
  (each event (get scenario :initial-events []) (schedule (event :at) (get event :priority 10) (event :kind) event))
  (while (not (empty? queue))
    (++ processed)
    (assert (<= processed limit) "Combat event limit reached.")
    (when (and cancelled (= 0 (% processed 32)) (cancelled)) (error "Cancelled."))
    (def event (pop queue))
    (advance (event :at))
    (case (event :kind)
      :decide (decide (actors (event :actor)))
      :release (release event)
      :effect (apply-effect event)
      :death (let [actor (actors (event :actor))]
               (when (and (alive? actor) (<= (actor :health) 0))
                 (put actor :dead-at at) (put actor :velocity 0)
                 (record :death {:actor (actor :id)})
                 (trigger (actors (actor :target)) actor :kill (string "death/" (actor :id)) 0)))
      :buff-expire (let [actor (actors (event :actor))]
                     (put (actor :buff-counts) (event :buff) (max 0 (- (get (actor :buff-counts) (event :buff) 0) (event :stacks)))))
      :expire (record :expire {:actor ((actors (event :actor)) :id)})
      (note (string "Unsupported event: " (event :kind)))))
  (advance duration)
  (record :end {})
  (def player (actors 0))
  (def opponent (actors 1))
  (def attack-damage (player :attack-damage))
  {:engine version :model identity :actors actors :trace trace :events (filter |(= (player :id) ($ :actor)) hits) :unsupported unsupported
   :assumptions ["Declared ability priority precedes basic attacks."
                 "Cooldowns start on cast unless an override declares otherwise."
                 "Ordinary attack windup is 30% unless configured."
                 "Projectile travel uses distance at release; collision geometry is omitted."
                 "Ability resource costs use the participant's configured resource pool."
                 "Parsed effects are estimates; unresolved effects are excluded and reported."]
   :damage (player :damage-dealt) :dps (/ (player :damage-dealt) duration)
   :attack-dps (/ attack-damage duration) :ability-dps (/ (- (player :damage-dealt) attack-damage) duration)
   :resource-left (player :resource)
   :metrics {:damage (player :damage-dealt) :damage-taken (player :damage-taken) :health (player :health)
             :healing (player :healed) :absorbed (player :absorbed) :control (opponent :control-time)
             :kill-time (opponent :dead-at) :death-time (player :dead-at)}})
