(import ./data-util :as util)
(import ./https :as https)
(import ./normalize :as normalize)
(import pshash :as hash)

(var data-dir nil)
(var default-version "16.19.1")
(def loaded @{})
(defn storage-limit []
  (def text (os/getenv "PS_DATA_LIMIT_MB" "5120"))
  (def megabytes (scan-number text))
  (assert (and (number? megabytes) (= megabytes (math/floor megabytes)) (<= 100 megabytes 1048576))
          "PS_DATA_LIMIT_MB must be a whole number from 100 to 1048576.")
  (* megabytes 1024 1024))
(defn directory [version snapshot]
  (assert (util/version? version) "Invalid patch identifier.")
  (assert (and (string? snapshot) (= 64 (length snapshot))
               (peg/match ~(* (some (range "09" "af")) -1) snapshot)) "Invalid snapshot identifier.")
  (string data-dir "/patches/" version "/" snapshot))

(defn available []
  (def root (string data-dir "/patches"))
  (if (os/stat root) (filter |(and (util/version? $) (os/stat (string root "/" $ "/current"))) (os/dir root)) []))

(defn load [version &opt snapshot]
  (assert data-dir "Initialize the runtime data directory first.")
  (assert (util/version? version) "Invalid patch identifier.")
  (def id (or snapshot (string/trim (slurp (string data-dir "/patches/" version "/current")))))
  (def key (string version "/" id))
  (or (loaded key)
      (do
        (def dir (directory version id))
        (def bytes (slurp (string dir "/package.jdn")))
        (def manifest (util/read-json (slurp (string dir "/manifest.json"))))
        (assert (= id (hash/sha256 bytes) (manifest "package_sha256")) "Corrupted data snapshot.")
        (def data (util/read-data (string dir "/package.jdn")))
        (assert (and (= 1 (data :schema)) (= version (data :patch))) "Incompatible data package.")
        (def package (merge data {:snapshot id :directory dir :manifest manifest
                                  :champion-map (tabseq [champion :in (data :champions)] (champion :id) champion)
                                  :item-map (tabseq [item :in (data :items)] (item :id) item)}))
        (put loaded key package)
        package)))

(defn initialize [directory seed]
  (storage-limit)
  (each key (keys loaded) (put loaded key nil))
  (set data-dir (util/mkdirs directory))
  (util/mkdirs (string data-dir "/patches"))
  (util/mkdirs (string data-dir "/jobs"))
  (when (and seed (os/stat seed))
    (each version (os/dir seed)
      (when (and (util/version? version) (not (os/stat (string data-dir "/patches/" version "/current"))))
        (util/copy-tree (string seed "/" version) (string data-dir "/patches/" version)))))
  (def patches (available))
  (assert (not (empty? patches)) "No cached patches. Set PS_SEED_DIR to the installed seed data directory.")
  (def candidates (if (some |(= default-version $) patches) [default-version ;patches] patches))
  (var selected nil)
  (each version candidates
    (unless selected
      (def result (protect (load version)))
      (when (first result) (set selected (result 1)) (set default-version version))))
  (assert selected "No usable data snapshots. Restore a retained package or reinstall the seed data.")
  selected)

(defn versions []
  (def path (string data-dir "/versions.json"))
  (def response (protect (https/get-async "https://ddragon.leagueoflegends.com/api/versions.json")))
  (when (first response)
    (def values (util/read-json (response 1)))
    (assert (and (indexed? values) (not (some |(not (util/version? $)) values))) "Invalid provider patch list.")
    (util/atomic-write path (response 1)))
  (if (os/stat path) (util/read-json (slurp path)) (available)))

# Executed only on a background worker. Publish the current pointer last.
(defn fetch [version staging progress cancelled &opt requester]
  (assert (util/version? version) "Invalid patch identifier.")
  (def request (or requester https/get))
  (def sources @[])
  (def missing @[])
  (var downloaded 0)
  (def quota (storage-limit))
  (def starting-size (util/tree-size data-dir))
  (defn obtain [url relative &opt optional]
    (when (cancelled) (error "Cancelled."))
    (def result (protect (request url cancelled)))
    (if (first result)
      (do
        (def bytes (result 1))
        (+= downloaded (length bytes))
        (assert (<= (+ starting-size downloaded) (- quota (* 8 1024 1024))) "Data storage allowance reached. Prune unused patches.")
        (util/write (string staging "/" relative) bytes)
        (array/push sources {"url" url "path" relative "sha256" (hash/sha256 bytes)})
        (util/read-json bytes))
      (if optional (do (array/push missing (string "Unavailable source: " relative)) nil)
        (error (string (result 1))))))
  (util/mkdirs staging)
  (def dd (string "https://ddragon.leagueoflegends.com/cdn/" version "/data/en_US/"))
  (def cd (string "https://raw.communitydragon.org/" (util/cdragon-version version) "/"))
  (progress {:message "Downloading champion and item catalog" :completed 0 :total 1})
  (def champion-data (obtain (string dd "champion.json") "sources/champions.json"))
  (def item-data (obtain (string dd "item.json") "sources/items.json"))
  (assert (and (util/provider-version? version (champion-data "version"))
               (= (champion-data "version") (item-data "version"))) "Provider patch mismatch.")
  (def runes (obtain (string dd "runesReforged.json") "sources/runes.json" true))
  (def summoners (obtain (string dd "summoner.json") "sources/summoners.json" true))
  (def champions @[])
  (def ids (sorted (keys (champion-data "data"))))
  (eachp [index id] ids
    (progress {:message (string "Downloading " id) :completed index :total (length ids)})
    (def name (string/ascii-lower id))
    (def objects (obtain (string cd "game/data/characters/" name "/" name ".bin.json?powerspike=1")
                         (string "sources/characters/" id ".json") true))
    (def detail (obtain (string dd "champion/" id ".json") (string "sources/abilities/" id ".json") true))
    (when detail (assert (util/provider-version? version (detail "version")) "Ability data patch mismatch."))
    (array/push champions (normalize/champion version ((champion-data "data") id) (or objects {}))))
  (def package {:schema 1 :parser normalize/parser-version :patch version :communitydragon (util/cdragon-version version)
                :champions champions
                :items (seq [id :in (sorted (keys (item-data "data")))] (normalize/item version id ((item-data "data") id)))
                :runes (or runes []) :summoners (if summoners (values (summoners "data")) [])
                :objectives [] :coverage missing :sources sources})
  (def bytes (util/encode-data package))
  (def id (hash/sha256 bytes))
  (util/write (string staging "/package.jdn") bytes)
  (util/write (string staging "/manifest.json") (util/encode-json
                                                  {"schema" 1 "patch" version "snapshot" id "parser" normalize/parser-version "package_sha256" id
                                                   "sources" sources "downloaded_at" (os/time) "initial" false}))
  (when (cancelled) (error "Cancelled."))
  (def destination (directory version id))
  (util/mkdirs (string data-dir "/patches/" version))
  (if (os/stat destination) (util/remove-tree staging) (os/rename staging destination))
  (util/atomic-write (string data-dir "/patches/" version "/current") id)
  {:patch version :snapshot id})
