(import ./validation :as v)
(import ./damage :as damage)
(import ./combat :as combat)

# A declared greedy strategy: spells in supplied priority order, then attacks.
# This searches item builds for this strategy, not all possible action orders.
(defn evaluate [stats target scenario abilities ranks]
  (def duration (v/nonnegative (scenario :duration) "duration"))
  (assert (> duration 0) "duration must be positive")
  (def include-attacks (get scenario :include-attacks true))
  (def rate (v/nonnegative (stats :attack-speed) "attack speed"))
  (when include-attacks (assert (> rate 0) "attack speed must be positive"))
  (def period (if include-attacks (/ 1 rate) math/inf))
  (def windup (if include-attacks (* (v/fraction (scenario :windup-fraction) "windup fraction") period) 0))
  (def distance (v/nonnegative (get scenario :distance 0) "distance"))
  (var resource (v/nonnegative (get scenario :resource (get stats :mp 0)) "resource"))
  (var at 0)
  (var attack-ready 0)
  (def ready @{})
  (def actions @[])
  (each spell abilities
    (assert (spell :id) "spell requires an ID")
    (assert (not (has-key? ready (spell :id))) "duplicate spell ID")
    (put ready (spell :id) 0)
    (assert (> (v/nonnegative (spell :cast-time) "spell cast time") 0)
            "automatic rotation requires a positive spell cast time")
    (assert (or (= (spell :cooldown-start) :start) (= (spell :cooldown-start) :end))
            "cooldown start must be explicit"))
  (while (< at duration)
    (assert (< (length actions) 10000) "rotation exceeds action limit")
    (var chosen nil)
    (var chosen-rank 0)
    (var next-time (if include-attacks (max at attack-ready) math/inf))
    (each spell abilities
      (def rank (get ranks (spell :slot) 0))
      (v/integer-between rank 0 (length (spell :base-damage)) "spell rank")
      (when (> rank 0)
        (def cost (v/nonnegative ((spell :cost) (- rank 1)) "spell cost"))
        (when (>= resource cost)
          (def spell-at (get ready (spell :id) 0))
          (if (<= spell-at (+ at 1e-9))
            (unless chosen (set chosen spell) (set chosen-rank rank))
            (set next-time (min next-time spell-at))))))
    (cond
      chosen
      (do
        (def travel (if (> (get chosen :missile-speed 0) 0)
                      (/ distance (chosen :missile-speed)) 0))
        (array/push actions {:at at :kind :spell :spell chosen :rank chosen-rank :travel-time travel})
        (-= resource ((chosen :cost) (- chosen-rank 1)))
        (put ready (chosen :id)
             (+ (if (= (chosen :cooldown-start) :end) (+ at (chosen :cast-time)) at)
                (damage/cooldown ((chosen :cooldown) (- chosen-rank 1)) (get stats :ability-haste 0))))
        (+= at (chosen :cast-time)))
      (and include-attacks (<= attack-ready (+ at 1e-9)))
      (do
        (array/push actions {:at at :kind :attack :windup windup
                             :travel-time (get scenario :attack-travel-time 0)})
        (set attack-ready (+ at period))
        (+= at windup))
      (set at next-time)))
  (def result (combat/simulate stats target {:duration duration :actions actions
                                             :resource (get scenario :resource (get stats :mp 0))}))
  (var attack-damage 0)
  (var ability-damage 0)
  (each event (result :events)
    (if (= :attack (event :source))
      (+= attack-damage (event :damage))
      (+= ability-damage (event :damage))))
  {:damage (result :damage) :dps (result :dps)
   :attack-dps (/ attack-damage duration) :ability-dps (/ ability-damage duration)
   :events (result :events) :actions (tuple ;actions) :resource-left (result :resource-left)
   :strategy :spell-priority-then-attacks})
