(import ./model :as model)
(import ./catalog :as catalog)
(import ../src/powerspike/data-util :as util)
(import ../src/powerspike/scenario :as scenario)
(import ../src/powerspike/scenario-wire :as wire)
(import ../src/powerspike/search :as search)
(import ../src/powerspike/packages :as packages)
(import ../src/powerspike/calibration :as calibration)
(defn run [settings]
  (catalog/initialize (settings :data-dir) (settings :seed-dir))
  (def path (settings :input-file))
  (assert (<= (or (os/stat path :size) math/inf) 65536) "Input JSON must fit within 64 KB.")
  (def result
    (case (settings :mode)
      :simulate (scenario/simulate (wire/decode (slurp path)))
      :calibrate (calibration/read path)
      :optimize
      (do (def record (util/read-json (slurp path)))
        (assert (and (= "powerspike-optimization" (get record "format")) (= 1 (get record "version"))) "Unsupported optimization document.")
        (def definition (wire/decode (util/encode-json (get record "scenario-document"))))
        (def state (model/state-from-definition definition))
        (def options (model/search-options (get record "constraints" {}) state))
        (search/run (packages/load (definition :patch) (definition :snapshot)) definition options (fn [p] nil) (fn [] false)))))
  (print (util/encode-json result)))
